# Generated by Django 5.2 on 2025-07-09 06:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The detailed text content of the feedback.')),
                ('rating', models.IntegerField(help_text='A numerical rating from 1 to 5.', validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1.'), django.core.validators.MaxValueValidator(5, message='Rating cannot be more than 5.')])),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time when the feedback was submitted.')),
                ('user', models.ForeignKey(help_text='The user who provided this feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
